### PR TITLE
qp: faster compat popcount

### PR DESCRIPTION
**Pull request by vavrusa**

### CODE REVIEW

**Comment by fanf2** [comment]
Thanks for the contribution! Is that the trick used by LLVM?

I am surprised you removed the SWAR code for doing two 16 bit popcounts in parallel - I would have expected it to be faster than calling popount() twice.

**Comment by vavrusa** [comment]
It still does the 2 popcounts in parallel, but the accumulation of the two halves is different and less intuitive. See [AMD64 optimizations guide](http://support.amd.com/TechDocs/25112.PDF) 8.6 _"Efficient Implementation of Population-Count Function in 32-Bit Mode"_.

But I just realized that this isn't needed for the 16bit popcount, so I might as well get it back to save two instructions.

**Comment by fanf2** [comment]
I've pushed a little change which makes the SWAR popcount slightly more efficient.

**Comment by vavrusa** [comment]
Just checked - performance close to this PR, slightly slower but insignificant :)

**Comment by fanf2** [comment]
Interesting. My guess is we are seeing the effect of instruction-level parallelism: there are enough arithmetic units that the CPU can do two hand-coded popcount()s as fast as one. And two separate popcount()s do not have coupled data dependencies at the start and end like the SWAR one does.

**Comment by vavrusa** [comment]
I think so, yes.

**Comment by fanf2** [comment]
Thanks for your patch and feedback!

**Pull request closed without merging**
